export var seo_text = {
  listing_categories_page_title: 'Listing Categories',
  listing_categories_page_description: 'All listing categories.',
  add_listing_page_title: 'Add Listing',
  add_listing_page_description: 'Add your new listing',
  edit_listing_page_title: 'Edit Listing',
  edit_listing_page_description: 'Edit your listing',
  checkout_page_title: 'Checkout',
  checkout_page_description: 'Checkout your product',
  my_account_page_title: 'My Account',
  my_account_page_description: 'Account details',
  add_account_page_title: 'Create Account',
  add_account_page_description: 'Create new account for upload your listings.',
  edit_account_page_title: 'Edit Account',
  edit_account_page_description: 'Edit your account.',
  edit_profile_page_title: 'Edit Profile',
  edit_profile_page_description: 'Edit your profile.',
  search_page_title: 'Search Listings',
  search_page_description: 'Search your listings.',
  account_orders_page_title: 'Account Orders',
  account_orders_page_description: 'All orders of your account.',
  account_order_details_page_title: 'Account Order Details',
  account_order_details_page_description: 'Order details',
  orders_page_title: 'Orders',
  orders_page_description: 'All orders list.',
  order_details_page_title: 'Order Details',
  order_details_page_description: 'Order details',
  add_review_page_title: 'Add Review',
  add_review_page_description: 'Add your review.',
  invite_page_title: 'Invite',
  invite_page_description: 'Invite your friends.',
  payout_page_title: 'Payout',
  payout_page_description: 'Payout',
  wishlist_page_title: 'Wishlist',
  wishlist_page_description: 'Wishlist listings.',
};
