export var TYPE_CONSTANT = {
  MARKETPLACE_TYPE: '',
  MARKETPLACE_MODULE: '',
  THEME: 1,
  AUTH_KEY: '',
  META_TITLE: '',
  META_DESCRIPTIONS: '',
  META_ACCOUNT_TITLE: '',
  META_ACCOUNT_DESCRIPTIONS: '',
  META_LISTING_TITLE: '',
  META_LISTING_DESCRIPTION: '',
  META_LISTING_CATEGORY_TITLE: '',
  META_LISTING_CATEGORY_DESCRIPTION: '',
};
